/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Componente.ComponentResizer;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import Desvanecimiento.Desvanecimiento;
/**
 *
 * @author master
 */
public class PanelControl extends javax.swing.JFrame {

    /**
     * Creates new form PanelControl
     */
    private boolean menu;
    private int estado;
    private int Vertical_Y;
    private int Horizontal_X;
    private Dimension screenSize;
    private javax.swing.JLabel background;
    Desvanecimiento efecto;
    
    @SuppressWarnings("LeakingThisInConstructor")
    public PanelControl() {
        InicomsPreapred();
        setLocationRelativeTo(null);
        efecto = new Desvanecimiento();
        efecto.Abrir(this, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSistema = new javax.swing.JPopupMenu();
        MenuRestaurar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JLabel();
        BtnMaximizar = new javax.swing.JLabel();
        BtnMinimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        MenuRestaurar.setText("Restaurar");
        MenuSistema.add(MenuRestaurar);

        jMenuItem2.setText("Minimizar");
        MenuSistema.add(jMenuItem2);

        jMenuItem3.setText("Maximizar");
        MenuSistema.add(jMenuItem3);

        jMenuItem4.setText("Cerrar");
        MenuSistema.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(20, 20, 20));
        jPanel3.setOpaque(false);
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Icons/favicon.png"))); // NOI18N
        jLabel1.setComponentPopupMenu(MenuSistema);

        Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Administrador");
        Title.setIconTextGap(15);

        BtnCerrar.setBackground(new java.awt.Color(229, 33, 33));
        BtnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Icons/Cerrar.png"))); // NOI18N
        BtnCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrar.setOpaque(true);
        BtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCerrarMouseExited(evt);
            }
        });

        BtnMaximizar.setBackground(new java.awt.Color(51, 51, 51));
        BtnMaximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Icons/Maximizar.png"))); // NOI18N
        BtnMaximizar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        BtnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMaximizar.setOpaque(true);
        BtnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMaximizarMouseExited(evt);
            }
        });

        BtnMinimizar.setBackground(new java.awt.Color(51, 51, 51));
        BtnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Icons/Minimizar.png"))); // NOI18N
        BtnMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnMinimizar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        BtnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMinimizar.setOpaque(true);
        BtnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(BtnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        if (getX() == 0 && getY() == 0) {
        } else {
            setLocation(evt.getXOnScreen() - Horizontal_X, evt.getYOnScreen() - Vertical_Y);
            if (evt.getYOnScreen() == 0) {
                Maximizar();
            }
        }
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        Vertical_Y = evt.getY();
        Horizontal_X = evt.getX();
    }//GEN-LAST:event_jPanel3MousePressed

    private void BtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            efecto.Cerrar(this, 20);
        }
    }//GEN-LAST:event_BtnCerrarMouseClicked

    private void BtnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaximizarMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            if (estado == 0) {
                Maximizar();
            } else {
                Normal();
            }
        }
    }//GEN-LAST:event_BtnMaximizarMouseClicked

    private void BtnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            efecto.Ocultar(this, 20);
        }
    }//GEN-LAST:event_BtnMinimizarMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            if (evt.getClickCount() == 2) {
                if (estado == 0) {
                    Maximizar();
                } else {
                    Normal();
                }
            }
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void BtnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaximizarMouseEntered
        BtnMaximizar.setBackground(new Color(143, 175, 220));
    }//GEN-LAST:event_BtnMaximizarMouseEntered

    private void BtnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMaximizarMouseExited
        BtnMaximizar.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_BtnMaximizarMouseExited

    private void BtnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseEntered
        BtnMinimizar.setBackground(new Color(143, 175, 220));
    }//GEN-LAST:event_BtnMinimizarMouseEntered

    private void BtnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinimizarMouseExited
        BtnMinimizar.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_BtnMinimizarMouseExited

    private void BtnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseEntered
        BtnCerrar.setBackground(new Color(229, 75, 75));
    }//GEN-LAST:event_BtnCerrarMouseEntered

    private void BtnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarMouseExited

        BtnCerrar.setBackground(new Color(229, 33, 33));
    }//GEN-LAST:event_BtnCerrarMouseExited

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        fondo1();
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        fondo2();
    }//GEN-LAST:event_formFocusLost

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        if(estado==1){
            Maximizar();
        }else{
            Normal();
        }
        efecto.Mostrar(this, 20);
    }//GEN-LAST:event_formWindowDeiconified

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnCerrar;
    private javax.swing.JLabel BtnMaximizar;
    private javax.swing.JLabel BtnMinimizar;
    private javax.swing.JMenuItem MenuRestaurar;
    private javax.swing.JPopupMenu MenuSistema;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void fondo1() {
        background.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/UI_Icons/BackgroundTraslucido1.png")));
        background.updateUI();
    }

    private void fondo2() {
        background.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/UI_Icons/BackgroundTraslucido2.png")));
        background.updateUI();
    }

    private void Maximizar() {
        estado = 1;
        setLocation(0, 0);
        float t = (float) screenSize.height / (float) 100;
        t = (float) (t * 94.78);
        setSize(screenSize.width, (int) (t));
    }

    private void Normal() {
        estado = 0;
        setSize(getPreferredSize());
        setLocationRelativeTo(null);
    }

    private void InicomsPreapred() {
        initComponents();
        favicon();
        menu=true;
        estado = 0;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        AWTUtilities.setWindowOpaque(this, false);
        background = new javax.swing.JLabel();
        fondo1();
        getLayeredPane().add(background, javax.swing.JLayeredPane.FRAME_CONTENT_LAYER);
        background.setBounds(0, 0, screenSize.width, screenSize.height);
        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        cr.setSnapSize(new Dimension(10, 10));
        cr.setMaximumSize(getMaximumSize());
        cr.setMinimumSize(getMinimumSize());
    }
    
    private void favicon() {
        javax.swing.ImageIcon ImageIcon = new javax.swing.ImageIcon(getClass().getResource("/UI_Icons/favicon.png"));
        setIconImage(ImageIcon.getImage());
    }
    
}
