/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import Desvanecimiento.Desvanecimiento;
import java.awt.Color;

/**
 *
 * @author karam
 */
public class mainInterface extends javax.swing.JFrame {

    int posX, posY;
    Desvanecimiento desv;

    public mainInterface() {
        initComponents();
        desv = new Desvanecimiento();
        desv.Abrir(this, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        ls_2 = new javax.swing.JLabel();
        ls_1 = new javax.swing.JLabel();
        prob_1 = new javax.swing.JLabel();
        miu_1 = new javax.swing.JLabel();
        lam_1 = new javax.swing.JLabel();
        calc_btn = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        miu_txt = new javax.swing.JTextField();
        miu_lbl = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lambdaa_txt = new javax.swing.JTextField();
        lambda_lbl = new javax.swing.JLabel();
        inputBg = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        dragged_zone = new javax.swing.JPanel();
        main_lbl = new javax.swing.JLabel();
        divisorLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(11, 179, 137));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Teoría de colas");
        mainContainer.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 440, 40));

        ls_2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ls_2.setForeground(new java.awt.Color(11, 179, 137));
        ls_2.setText("Promedio de clientes en espera (Ls):");
        mainContainer.add(ls_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        ls_1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ls_1.setForeground(new java.awt.Color(11, 179, 137));
        ls_1.setText("Promedio de clientes en espera (Ls):");
        mainContainer.add(ls_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        prob_1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        prob_1.setForeground(new java.awt.Color(11, 179, 137));
        prob_1.setText("Probabilidad (ρ):");
        mainContainer.add(prob_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        miu_1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        miu_1.setForeground(new java.awt.Color(11, 179, 137));
        miu_1.setText("Media de atención por hora (μ):");
        mainContainer.add(miu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        lam_1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lam_1.setForeground(new java.awt.Color(11, 179, 137));
        lam_1.setText("Media de clientes por hora (λ):");
        mainContainer.add(lam_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        calc_btn.setBackground(new java.awt.Color(37, 54, 82));
        calc_btn.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        calc_btn.setForeground(new java.awt.Color(11, 179, 137));
        calc_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calc_btn.setText("Calcular");
        calc_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calc_btn.setOpaque(true);
        calc_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calc_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calc_btnMouseExited(evt);
            }
        });
        mainContainer.add(calc_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 40));
        mainContainer.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 120, -1));

        miu_txt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        miu_txt.setForeground(new java.awt.Color(11, 179, 137));
        miu_txt.setBorder(null);
        miu_txt.setCaretColor(new java.awt.Color(255, 255, 255));
        miu_txt.setOpaque(false);
        mainContainer.add(miu_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 120, 40));

        miu_lbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        miu_lbl.setForeground(new java.awt.Color(11, 179, 137));
        miu_lbl.setText("Capacidad de atención por hora:");
        mainContainer.add(miu_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        mainContainer.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 110, -1));

        lambdaa_txt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lambdaa_txt.setForeground(new java.awt.Color(11, 179, 137));
        lambdaa_txt.setBorder(null);
        lambdaa_txt.setCaretColor(new java.awt.Color(255, 255, 255));
        lambdaa_txt.setOpaque(false);
        mainContainer.add(lambdaa_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 110, 40));

        lambda_lbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lambda_lbl.setForeground(new java.awt.Color(11, 179, 137));
        lambda_lbl.setText("Llegada de clientes por hora:");
        mainContainer.add(lambda_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        inputBg.setBackground(new java.awt.Color(37, 54, 82));
        inputBg.setOpaque(true);
        mainContainer.add(inputBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 640));

        closeBtn.setBackground(new java.awt.Color(21, 38, 64));
        closeBtn.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(11, 179, 137));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setOpaque(true);
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        mainContainer.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 50, 40));

        dragged_zone.setBackground(new java.awt.Color(21, 38, 64));
        dragged_zone.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragged_zoneMouseDragged(evt);
            }
        });
        dragged_zone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragged_zoneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout dragged_zoneLayout = new javax.swing.GroupLayout(dragged_zone);
        dragged_zone.setLayout(dragged_zoneLayout);
        dragged_zoneLayout.setHorizontalGroup(
            dragged_zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        dragged_zoneLayout.setVerticalGroup(
            dragged_zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        mainContainer.add(dragged_zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 40));

        main_lbl.setBackground(new java.awt.Color(21, 38, 64));
        main_lbl.setOpaque(true);
        mainContainer.add(main_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        divisorLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divisorLbl1.setForeground(new java.awt.Color(255, 255, 255));
        divisorLbl1.setText("----------------------------------------------------------------------------------");
        mainContainer.add(divisorLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dragged_zoneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragged_zoneMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - posX, y - posY);
    }//GEN-LAST:event_dragged_zoneMouseDragged

    private void dragged_zoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragged_zoneMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_dragged_zoneMousePressed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        desv.Cerrar(this, 5);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        new ColorTransition(closeBtn, new Color(21, 38, 64), new Color(11, 179, 137), new Color(11, 179, 137), new Color(21, 38, 64)).execute();
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        new ColorTransition(closeBtn, new Color(11, 179, 137), new Color(21, 38, 64), new Color(21, 38, 64), new Color(11, 179, 137)).execute();
    }//GEN-LAST:event_closeBtnMouseExited

    private void calc_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calc_btnMouseEntered
        new ColorTransition(calc_btn, new Color(37, 54, 82), new Color(11, 179, 137), new Color(11, 179, 137), new Color(37, 54, 82)).execute();
    }//GEN-LAST:event_calc_btnMouseEntered

    private void calc_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calc_btnMouseExited
        new ColorTransition(calc_btn, new Color(11, 179, 137), new Color(37, 54, 82), new Color(37, 54, 82), new Color(11, 179, 137)).execute();
    }//GEN-LAST:event_calc_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calc_btn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel divisorLbl1;
    private javax.swing.JPanel dragged_zone;
    private javax.swing.JLabel inputBg;
    private javax.swing.JLabel lam_1;
    private javax.swing.JLabel lambda_lbl;
    private javax.swing.JTextField lambdaa_txt;
    private javax.swing.JLabel ls_1;
    private javax.swing.JLabel ls_2;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JLabel main_lbl;
    private javax.swing.JLabel miu_1;
    private javax.swing.JLabel miu_lbl;
    private javax.swing.JTextField miu_txt;
    private javax.swing.JLabel prob_1;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
